name: CI
# Triggers the workflow on push / pull request events / manual trigger
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} - ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=50%

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          flags: ${{ matrix.os }}

      - name: Build
        run: yarn build
